title: Transgender Resource Wiki
#description: transgender resource wiki description
theme: just-the-docs

url: https://transgender-resource-wiki.github.io/

#logo: "/assets/images/skinny_long_test_image.png"

favicon_ico: "/assets/favicon.ico"

search.heading_level: 3

aux_links:
  Temp: https://transgender-resource-wiki.github.io/
aux_links_new_tab: true
