title: Transgender Resource Wiki
#description: transgender resource wiki description
theme: just-the-docs

url: https://just-the-docs.github.io

favicon_ico: "/assets/favicon.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
